# Generated by Django 4.1.2 on 2022-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('bestwork', models.BooleanField(verbose_name=False)),
            ], 
        ),
    ]
