# Generated by Django 4.1.2 on 2022-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_details',
            name='bestwork',
            field=models.BooleanField(default=False),
        ),
    ]
